### PR TITLE
list fixtures and provide getters for them

### PR DESCRIPTION
**Pull request by smacker**
Proposal for API of this repo.

With it we can do:
```go
f := fixtures.GetByName("basic")

// some unit test
req := &ChangesRequest{
    Base: &f.CommitRevision.Base,
    Head: &f.CommitRevision.Head,
}

// or another one
e := f.ReviewEvent("github")

// or integration test (json)
type mockEvent struct {
    Event string `json:"event"`
     *lookout.ReviewEvent
}
func (e *mockEvent) String() string {
    // json.Marshal here
}

e := &mockEvent{Event: "review", ReviewEvent: f.ReviewEvent("")}
suite.sendEvent(e.String())
```

and we can add tar files with something similar to `DotGit` of go-git-fixtures later.

### CODE REVIEW

**Comment by carlosms** [comment]
This makes sense to me, and it fits with our current code.

But I wonder if we should force us to decouple this from our lookout structures. Maybe it would be better to store `github.PullRequest` here, and get the `lookout.ReviewEvent` with `castPullRequest` from `utils.go` (exporting it if needed).

This way the fixtures will be agnostic to any internal changes we do to our structures. And they could be used to find bugs if, for example, we change how we assign `lookout.ReviewEvent.InternalID`.

**Comment by smacker** [comment]
To create `github.PullRequest` we actually need to scrab github. I mentioned it in here: https://github.com/src-d/lookout-test-fixtures/pull/5/files#diff-7ddfb3e035b42cd70649cc33393fe32cR107

We will need another issue to implement it.

I see your point about `InternalID`. But do you suggest to get rid off `Review/PushEvent` only or `CommitRevision` too? In my opinion `CommitRevision` is useful to have and it is a part of sdk that shouldn't change.

**Comment by carlosms** [comment]
Ideally I would also get rid of `CommitRevision`. Even if the structure does not change, maybe at some point we refactor how we fill it from a github PR and accidentally break it without realizing.

I'm assuming that we can call `cast` and then `e.Revision()` easily. If this would require too much complexity, we could of course keep `CommitRevision` and use it in specific tests.

**Comment by smacker** [comment]
CommitRevision is independent from github and any converters.
It's just a pointer to commit in a repository.
The intention of this repository is to test not only github provider but the core too.

I have removed Events and changed import from lookout to sdk.

**Comment by smacker** [comment]
All required by https://github.com/src-d/lookout/issues/134 fixtures are created and listed here.

@carlosms please another pass

**Comment by smacker** [comment]
Great. Then I'm merging so we will have some basic api that we can improve later.

**Pull request merged**
